[google_credentials]
type = "service_account"
project_id = "sincere-elixir-443511-g5"
private_key_id = "f3b9e06b72820931d11e9d11b6644b50a38bbd67"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEuwIBADANBgkqhkiG9w0BAQEFAASCBKUwggShAgEAAoIBAQCk7Xikp8mQBcxS
uon6S4OojUu9IkgCc8/ykhYwslp58pjsA5L27UdTPMv0pebW1bB08Cbxe8kaVjgt
pljBdLTNx0a0u0bLxX3pReyTe9oFyOowfadGamyX/VTL/361PJRU3LwNGiV/0SIz
ijX4IYwoqo2unEluSYLZS9Sk7VG3pFzqZNOm7VQTttZVoCr4jZKi5Tm21U9roU31
7fDB3r5nffL3oGXd5to/1RaZS7v0O3eWI93h4Zl1K37QK9simMD+kUyiATAEXnXV
ZPgnTR1p44r+KGZutpAJpj5v3hyKCiuMeTy1tTjGQIjbL31JWKya/aIX0SiPTygC
7yhW1hOzAgMBAAECgf998tuu4nOLCOKASvQTsJdaoIy2Yvea59Zl6CoKBioR9rHR
iukwqQNPDZ6ztf4TEh0vMDaNM3rgIffE5MPi+L0aaJQWcO4frzH4cu23s11MDaLK
ZSrZG2zSpSOcpgCdZyXfqLHzT4RTl+IGegW89+GRLK4GKlPpZToHt2Eskg9VrXLv
FwFFz3YRcjF2TRWUwSUdNuIye+cOAzgwonLSYrEQluOhRsQcGydvQcXqX8fdbMGZ
vcd6tJBQ2XSz/DcSIvHlYdpl9Wm8wD4gw/7P2nmSfLxZ/EQ9WjrMrxGMYt8WazAh
mMr4PS+V5w7m6QRz5IwKCFOzWcZ4izUNXu7efikCgYEA6Sfpot3XiIpt+4fmubTX
Qowab7CWZ1zmkFdZkS3o5gt6tEo1hgSIf+uQk59r+04a61ABf8gYmYshO+539L1D
hrgcz0hxRtooVBOhDG1RhZCqqhsMg+laRyTLzz7Cd+2xOyli9mON1dV73ZdqoQRY
oDzQDG4nNG/eojtPaZDR1rkCgYEAtRY8apTyybsqZRJ6hwZg5tlueZuyqc6tSXd8
nyTfkQ8KgdPUbBxRkUX66ONrm6vAJMsMQ59e4HWckLnXXNQtRLVUvH3RoYrloEdR
1gTR+DEBek4x/bmVSVmCN+Porc+w94YRyn1TDL7kkAWcX2UzHiJ+SrfV2irOkhgN
wmM/x8sCgYBT6PtalABXsYo3dgeBWiYGWynAfIsElBieZfFkIGOrNwJoFDUDEGqX
rw2PM1bHUKq7eUWw2TCRQdMqIH6nY94DhAtKRkYOO8E70Pyq3kTyjsf9BFMSvk6x
P/rhkTKnurGIGzL0fYu0I2q6qx3C6S+EK56sepA9fO1g8Xt5AJekcQKBgQCX+BQ1
wdBKuZbngW1wWUsDEJ/k0GRMmxTT3cGo8NHqM3w23eWb4NwXFWpu/UP2PVmfxwMA
0QNXTXxZ/Iwe7DUdPyvgj5pYfm8cZh3ohN0M81txH6RWcOM2zjY43zwKeYzi/RF7
JFeJD75Sm1LSv+P5OytPWx3N3DTFaAhMBOympwKBgALwZ3vvmvimQ4CXLe575S0J
iPG0mt73wtC6NTiOZlyaMZm3Pplz0IuROnMdfjk4bNkUDaT1GF0KUopk40v7mZ1I
M5ZHAgHozvCDQ6hA5RQh8r6KRtBucYX4qUSHdrTepKROERaVXp7+gJC0WhgGRgfs
XMD6zDbSXCiD+coy1rQc
-----END PRIVATE KEY-----
"""
client_email = "test-694@sincere-elixir-443511-g5.iam.gserviceaccount.com"
client_id = "111539439924020147647"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/test-694%40sincere-elixir-443511-g5.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

[groq_api]
private_key_id = "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"
